#!/bin/sh
set -eu
case "$1" in
    remove|purge)
        rm -f /opt/sv-burpsuite/burpsuite.jar /usr/share/pixmaps/sv-burpsuite.svg /usr/share/pixmaps/sv-burpsuite.png
        rmdir /opt/sv-burpsuite 2>/dev/null || true
        ;;
esac
#DEBHELPER#
